# fly.toml app configuration file generated for onetimechat-front on 2023-12-04T08:24:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "onetimechat"
primary_region = "waw"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
