name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag app

    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: app
        username: "{{ DOCKER_REGISTRY_LOGIN }}"
        password: "{{ DOCKER_REGISTRY_PASSWORD }}"
        registry: docker.pkg.github.com
