name: Docker Image CI

on: [push]

jobs:
  build_app:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: "Backend: Build and publish Docker image"
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ddoroshev/onetimechat/app
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: "ghcr.io"
        buildoptions: "--pull"

  build_front:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: "Frontend: Build and publish Docker image"
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ddoroshev/onetimechat/front
        workdir: front
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: "ghcr.io"
        buildoptions: "--pull"
